ubuntu:
    class: 'App\Repository\PxeLinuxRepository'
    config:
        label: 'Ubuntu {dist} Live Boot ({arch})'
        boot: 'casper'
        imgargs:
            - '{vmlinu}'
            - 'initrd={initrd}'
            - 'boot={boot}'
            - 'netboot=nfs'
            - 'nfsroot=${_nfs_server_}:${_nfs_base_path_}/{target}/{dist}/{arch}'
            - 'ip=dhcp'
            - 'splash'
            - 'quiet'
            - '--'
