parameters:
    pxe_boot:

        dirs:
            root: 'resources'
            tools: 'tools'
            media: 'media'

        tools:
            - 'memdisk'
            - 'wimboot'

        repositories:
            windows:
                class: 'App\Repository\PxeWindowsRepository'
                config:
                    label: 'Windows {dist} NetInstall ({arch})'
            ubuntu:
                class: 'App\Repository\PxeLinuxRepository'
                config:
                    label: 'Ubuntu {dist} Live Boot ({arch})'
                    boot: 'casper'
                    imgargs:
                        - '{vmlinu}'
                        - 'initrd={initrd}'
                        - 'boot={boot}'
                        - 'netboot=nfs'
                        - 'nfsroot=${nfsServerRoot}/{target}/{dist}/{arch}'
                        - 'ip=dhcp'
                        - 'splash'
                        - 'quiet'
                        - '--'
