parameters:
    pxe_boot:

        dirs:
            root: 'resources'
            tools: 'tools'
            media: 'media'

        tools:
            - 'memdisk'
            - 'wimboot'

        repositories:
            windows:
                class: 'App\Repository\PxeWindowsRepository'
                config:
                    label: 'Windows {dist} NetInstall ({arch})'
