parameters:
    pxe_boot:

        dirs:
            root: 'resources'
            tools: 'tools'
            media: 'media'

        tools:
            - 'memdisk'
            - 'wimboot'

        repositories:
