parameters:
    pxe_menu:
        title: 'PXE Boot Service - iPXE ${version} (${_arch_}) - ${_mode_} boot mode'
        menu:
            - {type: 'gap', label: 'Windows Systems'}
            - {type: 'repository', target: 'windows'}
            - {type: 'gap'}
            - {type: 'gap', label: 'Linux Systems'}
            - {type: 'repository', target: 'ubuntu'}
            - {type: 'gap', visibility: 'bios'}
            - {type: 'gap', label: 'Tools', visibility: 'bios'}
            - {type: 'repository', target: 'memtest86p'}
            - {type: 'repository', target: 'memtest86'}
