parameters:
    pxe_boot:

        dirs:
            root: 'resources'
            tools: 'tools'
            media: 'media'

        tools:
            - 'memdisk'
            - 'wimboot'

        repositories:
            windows:
                class: 'App\Repository\PxeWindowsRepository'
                config:
                    label: 'Windows {dist} NetInstall ({arch})'
                    netinstall: true

            ubuntu:
                class: 'App\Repository\PxeLinuxRepository'
                config:
                    label: 'Ubuntu {dist} Live Boot ({arch})'
                    boot: 'casper'
                    imgargs:
                        - '{vmlinu}'
                        - 'initrd={initrd}'
                        - 'boot={boot}'
                        - 'netboot=nfs'
                        - 'nfsroot=${_nfs_server_}:${_nfs_base_path_}/{target}/{dist}/{arch}'
                        - 'ip=dhcp'
                        - 'splash'
                        - 'quiet'
                        - '--'

            memtest86p:
                class: 'App\Repository\PxeMemdiskRepository'
                config:
                    label: 'Memtest86+ {dist} Memory Diagnostic Boot ({arch})'
                    iso: 'boot.iso'
                    imgargs:
                        - memdisk
                        - iso
                        - raw

            memtest86:
                class: 'App\Repository\PxeMemdiskRepository'
                config:
                    label: 'Memtest86 {dist} Original Memory Diagnostic Boot ({arch})'
                    iso: 'boot.iso'
                    imgargs:
                        - memdisk
                        - iso
                        - raw
